plugin:
    name: 'webbook.gdpr::lang.plugin.name'
    description: 'webbook.gdpr::lang.plugin.description'
    author: WebBook
    icon: icon-university
    homepage: 'https://github.com/WEBBOOK-plugins/gdpr'
permissions:
    webbook.gdpr.access_cookies_settings:
        label: 'webbook.gdpr::lang.permissions.access_cookies_settings'
        tab: 'webbook.gdpr::lang.plugin.name'
